{
 "title": "Udacity",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "API health check ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"http://3.20.239.32\"}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "instance:node_cpu:rate:sum{instance=\"10.100.2.87:9100\"}"
    }
   ]
  },
  {
   "title": "Network Received in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "instance:node_network_receive_bytes:rate:sum{instance=\"10.100.2.87:9100\"}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "node_disk_io_now{instance=\"10.100.2.87:9100\"}"
    }
   ]
  },
  {
   "title": "Memory in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"10.100.2.87:9100\"}"
    }
   ]
  }
 ]
}